# Generated by Django 6.0.2 on 2026-02-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanic',
            name='vehicle_type',
            field=models.CharField(choices=[('2W', '2 Wheeler'), ('4W', '4 Wheeler'), ('EV', 'EV Vehicle')], default='4W', help_text='Type of vehicles this mechanic services', max_length=3),
        ),
    ]
